# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the HTML file to the Nginx server's default location
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
